### ISSUE TITLE
Register package on code.dlang.org, please.

### ISSUE THREAD

**Issue by nin-jin** [nordlow/phobos-next#1]
http://code.dlang.org/register_package

You must add git tag like "v1.0.0".

Then everybody can use this package as dependency:

```json
"dependencies" : {
    "phobos-next" : "~>1.0.0"
}
```

**Comment by nordlow** [comment]
I've added an pushed a tag via Git and registered on code.dlang.org but version doesn't show up in code.dlang.org. What have I missed?

**Comment by nordlow** [comment]
Now it work: http://code.dlang.org/packages/phobos-next

**Comment by nin-jin** [comment]
Thank you :-)
