### ISSUE TITLE
a lot of cool stuff

### ISSUE THREAD

**Issue by wilzbach** [nordlow/phobos-next#2]
hi @nordlow - I made a pass through phobos-next and I tried to filter out stuff that I think is generally useful and hopefully can find it's way into Phobos. 

edit: [moved to the wiki](https://github.com/nordlow/phobos-next/wiki/Existing)

**Comment by nordlow** [comment]
Thanks. I'll looking it. 

- Andrei thinks the name `substitute()` is currently preferred over `replace` to distinguish lazy from non-lazy.
- Note that `SlidingSplitter` work correctly with UTF-8, that is it supports bidirectional access. I'm guessing your `RingBuffer` would have to support this too if you want to get it into Phobos. I'm using `SlidingSplitter` in my knowledge database to find meaningful word-splits of together-written words such as: `Rückblick` => [`Rück`, `blick`] ;)

**Comment by wilzbach** [comment]
As the year is closing, here's a summary of the progress & cool stuff to bring to Phobos for "next" year - I tried to group them after categories, s.t. it's easier to make actionable items out of them.
@nordlow how about enabling the wiki, s.t. it's easier to edit this list?

WIP
---------

method                    | staus         
-------------------------- | -------------- 
[SlidingSplitter](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/range_ex.d#L145) | [WIP PR at Phobos](https://github.com/dlang/phobos/pull/4027)
[traits.isPure](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L642) | [open Phobos PR](https://github.com/dlang/phobos/pull/4287)
debugging (aka [dbgio](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/dbgio.d)) | [open Phobos PR](https://github.com/dlang/phobos/pull/4318) (without `assumeNoGc`)
[Bound](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/bound.d) | [std.experimental.checkedint](https://github.com/dlang/phobos/pull/4613) |
[asStatic](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/array_ex.d#L54) | [Phobos PR](https://github.com/dlang/phobos/pull/4936)

Algorithms
-----------------

method                    | status         /description
-------------------------- | -------------- 
[horspool](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/horspool.d) | benchmark vs. Phobos
[radixsort](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/intsort.d#L35)
[SortedRange support for find](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/searching_ex.d#L16)
[permutations](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/permutations.d), [producs](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/products.d) | see also: [mir.combinators](docs.mir.dlang.io/latest/mir_combinatorics.html)
[trie](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/trie.d) | std.container?
[BitHashSet](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/bithashset.d)
[BitSet](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/bitset.d)
[sortBy](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/sort_ex.d#L20) | could be done by allowing `sort` to take a predicate with one parameter
[substitute/replace](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/substitution.d#L29) |
[either](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/algorithm_ex.d#L37) |
[overlap](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/algorithm_ex.d#L299)

CTFE / Introspection
---------------------------

(usually `std.traits`)

method                    | staus       /  description
-------------------------- | --------------
[Borrow](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/borrown.d) | Pretty cool!
[mustAddGCRange](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/container_traits.d#L92) |
[assumePure](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/hacks.d)
assumeNoGc
template [`Merge`](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/meta_ex.d#L86)
[traits.allSame](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L37) | - |
[traits.isComparable](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L475) | - |
[traits.isEquable](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L476) | - 
[traits.isCTFEable](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L553) | -
[traits.dimensionality](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L863) | -
[traits.asDynamicArray](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L226)
[traits.isGCPointer](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L16)
[traits.isLvalue](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L970)
[traits.isRvalue](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L974)
[modulo](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/modulo.d) |
[notnull](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/notnull.d) 
[`nullable`](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/typecons_ex.d#L21) | should be a trivial PR
[VariantPointerTo](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/variant_ex.d#L318)
[Vary](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/vary.d) | std.variant?
[nstate](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/nstate.d) | [Ternary](https://github.com/dlang/phobos/pull/4307) got into std.experimental.typecons this summer
[asTuple](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/range_ex.d#L782) | - |
[EnumUnion](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/enums.d#L73)
[ModArrayN](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/fixed_array.d)


Other
------

[deepdup](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/deepdup.d) 
[getopt help msg](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/getopt_ex.d) 
[leb128](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/leb128.d) | std.encoding?
[mangling](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/mangling.d) | std.mangling?
[pmap](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/parallelism_ex.d)
[isCapitalized](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/string_ex.d#L34) | std.string? 
[isNewline](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/traits_ex.d#L699) | std.ascii?
[`Rational`](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/rational.d) |


Rejected (for now)
---------

method                    | staus         |  description
-------------------------- | -------------- | ---------------
 stealFront,Back | [rejected Phobos PR](https://github.com/dlang/phobos/pull/4010) | Andrei still doesn't like it and since summer even `(r.popFront, r.front)` got deprecated :/
assertEqual            | [https://github.com/dlang/phobos/pull/4323](rejected Phobos PR) -> move your 
[DIP83](http://wiki.dlang.org/DIP83) to the new DIP system
 match/pattern matching | https://github.com/nordlow/phobos-next/blob/master/src/functional_ex.d
[bitop](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/bitop_ex.d) | [rejected Phobos PR](https://github.com/dlang/phobos/pull/4703) | rejected as trivia


Existing
-----------------

This is already part or other dedicated projects.

method                    | staus         |  description
-------------------------- | -------------- | ---------------
[allEqual](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/predicates.d#L81) | `e.findAdjacent!a != b".empty;` | one-liner
dropWhile |  never | aka `std.algorithm.find`
takeWhile | never |aka `std.algorithm.searching.until`
distinct | never | aka `std.algorithm.sorting.merge` and `uniq`
match/pattern matching | never | aka [visit](https://dlang.org/phobos/std_variant.html#.visit)
[cpuid](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/cpuid_ex.d) | mir-cpuid
[Fastq](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/fastq.d) | biod
[argmin/armax](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/numeric_ex.d#L126) | [min/maxElement](https://github.com/dlang/phobos/pull/4221)
[random](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/random_ex.d) | mir-random
[preslicer](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/slicing.d) | r.splitter.filter`!a.empty`
[geometric](https://github.com/nordlow/phobos-next/blob/7f15e4251ab679a3ae6e8e7c5c5cf815227f0bb4/src/geometry.d) | ndslice?

**Comment by nordlow** [comment]
Wow, what an initiative! I'm superglad somebody starts looking at the all useful stuff in phobos-next.

Can you elaborate on what you mean by _enabling the wiki_ ?

**Comment by wilzbach** [comment]
> Wow, what an initiative! I'm superglad somebody starts looking at the all useful stuff in phobos-next.

Hehe it's Christmas soon ;-)

> Can you elaborate on what you mean by enabling the wiki ? Do you mean moving your table into it?

It's seems I can't open the wiki:
https://github.com/nordlow/phobos-next/wiki

**Comment by nordlow** [comment]
Ahh, ok. I'm on to it.

**Comment by nordlow** [comment]
I created it: https://github.com/nordlow/phobos-next/wiki/Upcoming-add-ons-to-D's-standard-library-Phobos

**Comment by wilzbach** [comment]
> I created it: https://github.com/nordlow/phobos-next/wiki/Upcoming-add-ons-to-D's-standard-library-Phobos

Thanks!
Could you also give non-contributors write-access?

![image](https://cloud.githubusercontent.com/assets/4370550/21442949/90ea0690-c8a1-11e6-997f-9af919d4c3c8.png)

**Comment by nordlow** [comment]
Ahh, ok.

**Comment by nordlow** [comment]
Done.

**Comment by wilzbach** [comment]
> I unchecked it. Does it work now?

Yes - thanks a lot!

I created the pages after my initial grouping:

https://github.com/nordlow/phobos-next/wiki/1)-WIP-to-Phobos
https://github.com/nordlow/phobos-next/wiki/CTFE-Introspection-to-Phobos
https://github.com/nordlow/phobos-next/wiki/Other-to-Phobos
https://github.com/nordlow/phobos-next/wiki/Existing
https://github.com/nordlow/phobos-next/wiki/Rejected-(for-now)

The grouping / listing was arbitrary, so feel free to change/update it :)
Unfortunately the GH wiki doesn't have notifications, so we might want to use this thread for notification and communication.

There are a couple of bits like [DIP83](http://wiki.dlang.org/DIP83) that probably need more man power, so I am happy to help on these as well.

**Comment by nordlow** [comment]
Andrei has some comments on DIP-83 spec I haven't integrated. I'm on to it.

**Comment by wilzbach** [comment]
> Andrei has some comments on DIP-83 spec I haven't integrated. I'm on to it.

Note that there's [dwikiquery](https://github.com/dlang/DIPs/tree/master/tools/dwikiquery) - a tool that helps with the migration from the MediaWiki to Markdown (`dwikiquery fetch --id 83`).

As a preview: https://notehub.org/8l25k/edit

**Comment by andralex** [comment]
That's neat stuff, let's slice and dice it.
