### ISSUE TITLE
Testing Bound.

### ISSUE THREAD

**Issue by veelo** [nordlow/phobos-next#3]
Hei Per,

I'd like to test out Bound, but version 0.1.0 fails to compile due to an outdated import `phobos-next\src\algorithm_ex.d(1816,8): Error: module std.algorithm import 'aggregate' not found`. This seems to be fixed in master, but changing `"phobos-next": "~>0.1.0"` to `"phobos-next": "~master"` in my `dub.json` then also pulls in arsd ~master, which currently fails to compile with `arsd\arsd\curl.d(69,8): Error: module md5 is in file 'std\md5.d' which cannot be read`.

I think what is needed is to configure dub sub-packages (https://code.dlang.org/package-format?lang=json#sub-packages) and making a new release, so Bound can be used independent from the state of unrelated modules.

Thanks,
Bastiaan.

Edit: DMD32 D Compiler v2.073.0

**Comment by nordlow** [comment]
dub build works on master with latest stable dmd. Is a new release all that's missing?

**Comment by veelo** [comment]
I checked out master from git. On Windows, it fails like this:
`C:\D\code\phobos-next\phobos-next>dub build --arch=x86_64`
`WARNING: A deprecated branch based version specification is used for the dependency arsd. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.`
`Performing "debug" build using dmd for x86_64.`
`phobos-next ~master: building configuration "library"...`
`..\..\..\..\Users\bastiaan\AppData\Roaming\dub\packages\arsd-master\arsd\arsd\terminal.d(178,14): Deprecation: Implicit string concatenation is deprecated`
[snip]
`src\tempfs.d(16,12): Error: module core.sys.posix.stdlib import 'mkstemp' not found`
`dmd failed with exit code 1.`

Missing version() maybe?

**Comment by nordlow** [comment]
Put the definitions in a `version(linux)` for now. Ok?

**Comment by veelo** [comment]
Version 0.2.0 compiles for --arch=x86_64. However, a dependency on phobos_next does not work if 
I compile my project for 32 bit (which is a requirement), due to
```
phobos-next\src\trie.d(184,1): Error: static assert  "Currently requires a 64-bit CPU (size_t.sizeof == 8)"
```
I am really only interested in Bound, though.

BTW, can I ask why you compare to manually written out literal values instead of the .min and .max type properties in `template PackedNumericType` and `template BoundsType`?

**Comment by veelo** [comment]
I did a quick test:
```d
unittest
{
    import bound;
    auto o1 = bound.bound!(-3, 6);
    assert(o1.min == -3);
    assert(o1.max == 6);
    assert(o1.sizeof == 1);
    static assert(!__traits(compiles, bound.bound!(33, 6))); // 33 > 6
    //auto o2 = bound.bound!(10, 300);
    //assert(o2.min == 10);
    //assert(o2.max == 300);
    //assert(o2.sizeof == 2);
}
```
1) I think if you'd create a `phobos_next` package, I could do `import phobos_next.bound;` and then call `bound()` without it conflicting with a module name. Now I have to use `bound.bound()` it seems.
2) If I uncomment the last rows I get this exception:
```
bound.BoundOverflowException@C:\Users\bastiaan\AppData\Roaming\dub\packages\phobos-next-0.2.0\phobos-next\src\bound.d(96): Overflow at C:\Users\bastiaan\AppData\Roaming\dub\packages\phobos-next-0.2.0\phobos-next\src\bound.d:567 (payload: 0)
----------------
0x00007FF74A732B4F in bound.Bound!(ushort, 10, 300, false, true, true, false).Bound.checkAssign!(ushort, "C:\\Users\\bastiaan\\AppData\\Roaming\\dub\\packages\\phobos-next-0.2.0\\phobos-next\\src\\bound.d", 567).checkAssign at C:\Users\bastiaan\AppData\Roaming\dub\packages\phobos-next-0.2.0\phobos-next\src\bound.d(430)
0x00007FF74A7421A9 in bound.Bound!(ushort, 10, 300, false, true, true, false).Bound.__ctor!(ushort, "C:\\Users\\bastiaan\\AppData\\Roaming\\dub\\packages\\phobos-next-0.2.0\\phobos-next\\src\\bound.d", 567).this at C:\Users\bastiaan\AppData\Roaming\dub\packages\phobos-next-0.2.0\phobos-next\src\bound.d(319)
0x00007FF74A7417A2 in bound.bound!(10, 300, false, true, true, false).bound at C:\Users\bastiaan\AppData\Roaming\dub\packages\phobos-next-0.2.0\phobos-next\src\bound.d(567)
0
```
3) If I am not mistaken, there is no possibility to use a `Bound` type without also supplying it's base type. This is functionality that I'd miss. I wrote a rudimentary alternative (as excercise) which allows that (but probably has other deficiencies):
```d
module epcompat.ordinal;

import std.traits;

/**
    An integral type with specified inclusive bounds.

    No bounds checking is implemented.
*/
struct Ordinal(alias lower, alias upper) if (isIntegral!(typeof(lower)) &&
                                             isIntegral!(typeof(upper)))
{
    static assert(lower < upper);
    enum imp = r" _payload;
        alias _payload this;
        static auto min()
        {
            return lower;
        }
        static auto max()
        {
            return upper;
        }
        ";
    
    static if (lower < 0)
    {
        static if (lower >= byte.min && upper <= byte.max)
        {
            mixin("byte" ~ imp);
        }
        else static if (lower >= short.min && upper <= short.max)
        {
            mixin("short" ~ imp);
        }
        else static if (lower >= int.min && upper <= int.max)
        {
            mixin("int" ~ imp);
        }
        else
        {
            static assert(lower >= long.min && upper <= long.max);
            mixin("long" ~ imp);
        }
    }
    else
    {
        static if (lower >= ubyte.min && upper <= ubyte.max)
        {
            mixin("ubyte" ~ imp);
        }
        else static if (lower >= ushort.min && upper <= ushort.max)
        {
            mixin("ushort" ~ imp);
        }
        else static if (lower >= uint.min && upper <= uint.max)
        {
            mixin("uint" ~ imp);
        }
        else
        {
            static assert(lower >= ulong.min && upper <= ulong.max);
            mixin("ulong" ~ imp);
        }
    }
}

unittest
{
    Ordinal!(-3, 6) o1;
    assert(o1.min == -3);
    assert(o1.max == 6);
    assert(o1.sizeof == 1);
    static assert(!__traits(compiles, Ordinal!(33, 6)));    // 33 > 6
    Ordinal!(10, 300) o2;
    assert(o2.min == 10);
    assert(o2.max == 300);
    assert(o2.sizeof == 2);
    static assert(Ordinal!(0, 255).sizeof == 1);
    static assert(Ordinal!(-1, 255).sizeof == 2);
    static assert(Ordinal!(-1, 127).sizeof == 1);
    static assert(Ordinal!(-1, 70000).sizeof == 4);
}
```

**Comment by nordlow** [comment]
I'll look into this this week.

**Comment by veelo** [comment]
Thanks.

> Should the `package.d` be placed in the `src` dir

Yes.

> and just contain `module phobos_next`?

In addition it should publicly import the members of the pachage:
```
public import phobos_next.bound;
\\ etc.
```
The modules themselves should become
```
module phobos_next.bound;
\\ instead of module bound;
```
The file names themselves stay as they are, where they are.

**Comment by veelo** [comment]
Sorry for the confusion above. Please follow docs referenced in the edit, not my "help" :-)

**Comment by nordlow** [comment]
Sorry for not answering. I have little time right now.

**Comment by nordlow** [comment]
I've added the prefix `.nxt` to all the modules names.
