### ISSUE TITLE
Your mustAddGCRange copy from iz violates the BSL terms

### ISSUE THREAD

**Issue by BBasile** [nordlow/phobos-next#4]
Hi, i remember that we had talked about that on the NG and i indicated you what i do in IZ, my user lib. I'm glad to see that you have found this solution interesting to the point of copying it:

https://github.com/nordlow/phobos-next/blob/b394bc11babeb45c6dfadff938d46abacce6f984/src/container_traits.d#L92-L150

but you must include the original license (BSL), e.g mention the origin and the license from what's copied from IZ. This is required for BSL and when the code is not compiled (this is more or less what says the 2nd paragraph).

**Comment by BBasile** [comment]
I see that this repo has > 5000 commits and no license. Maybe it's time to choose one. Let's say that if you'd choose the BSL this would de facto solves this issue.

**Comment by nordlow** [comment]
Let's make it so!

**Comment by nordlow** [comment]
Where should I put the license tag? Will updating `dub.sdl` be sufficient?

**Comment by BBasile** [comment]
I see...but the sdl has no legal value. You must push the whole text file, with the same name and the same case, e.g like http://www.boost.org/LICENSE_1_0.txt

**Comment by BBasile** [comment]
You must push it at the root, i.e same place as the sdl

**Comment by BBasile** [comment]
also in the sdl you should set the property to "BSL-1.0", which is the correct short name.

**Comment by nordlow** [comment]
You mean the `license` property, I presume....

**Comment by nordlow** [comment]
Done.

**Comment by nordlow** [comment]
I'll add the txt-file aswell.

**Comment by nordlow** [comment]
License file added.

**Comment by nordlow** [comment]
Ok to close this now?

**Comment by BBasile** [comment]
Thanks. Also a wise decision for your stuff i'd say.

**Comment by nordlow** [comment]
Yes, :)
