### ISSUE TITLE
build error: unrecognized trait isCopyable

### ISSUE THREAD

**Issue by mw66** [nordlow/phobos-next#5]
.dub/packages/phobos-next-0.3.9/phobos-next/src/nxt/dynamic_array.d(67,16): Error: unrecognized trait isCopyable

...

missing import?

**Comment by nordlow** [comment]
What compiler version are you using?

**Comment by mingwugmail** [comment]
I see, I'm not on the bleeding edge.

Maybe if you add the import, the library will work with older versions of the compiler.

**Comment by nordlow** [comment]
Is latest stable dmd bleeding edge?

**Comment by mingwugmail** [comment]
I'm typically 1~2 versions behind.

If you add import, the library will work with older versions of the compiler.

**Comment by nordlow** [comment]
That is not sufficient since it's a new builtin trait.

If you really need this I can replace `__traits(isCopyable, T)` with `isCopyable!(T)` and add the import

    import std.traits : isCopyable;

**Comment by mingwugmail** [comment]
Never mind. I will upgrade when LDC proper release.

But for the library, maybe you can add an warning message after detecting version mis-match, so user won't be confused by the compiler error message.
